version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/parser"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.15
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.11
    - 7.13.12
    - 7.13.13
    - 7.13.15
    - 7.13.4
    - 7.13.9
  - dependency-name: "@babel/types"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.12
    - 7.13.14
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.6
    - 3.12.7
    - 3.12.8
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@babel/plugin-transform-parameters"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@babel/plugin-transform-spread"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
